# Settings and configurations that are common for minio containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
  command: server --console-address ":9001" --address ":9002" http://minio{1...2}/data{1...2}
  expose:
    - "9001"
    - "9002"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  postgres:
    image: postgres:16.6-alpine
    restart: unless-stopped
    ports:
      - 65432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: ["start-dev"]
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_LOG_LEVEL: INFO
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    ports:
      - 8080:8080
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  url-shortner:
    image: url-shortner:dev-1
    environment:
      KC_REALM_URL: "http://keycloak:8080/realms/url-shortner"
    restart: unless-stopped
    ports:
      - "8053:8053"

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio-lb:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./minio_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9001:9001"
      - "9002:9002"
    depends_on:
      - minio1
      - minio2
volumes:
  postgres_data:
  data1-1:
  data1-2:
  data2-1:
  data2-2: