services:
  postgres:
    image: postgres:16.6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: ["start-dev"]
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_LOG_LEVEL: INFO
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    ports:
      - 8080:8080
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  url-shortner:
    image: url-shortner:dev-1
    environment:
      KC_REALM_URL: "http://keycloak:8080/realms/url-shortner"
    restart: unless-stopped
    ports:
      - "8053:8053"
volumes:
  postgres_data: